
[tool.sullivan]
name = "my_project"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
description = "A new Python project"

[tool.sullivan.dependencies]
# Regular dependencies: essential libraries for the project to run
pydantic = "latest"

[tool.sullivan.dev-dependencies]
# Development dependencies: tools needed for development (e.g., formatting, linting)
black = "latest"
flake8 = "latest"

[tool.sullivan.test-dependencies]
# Test dependencies: libraries required for testing
pytest = "latest"

[tool.sullivan.scripts]
# Entry point script for the project
main = "src/main.py"

[tools.sullivan.optimization]
level = "O"

[tool.sullivan.python]
# Python version specification: default is '>=3.6,<4.0'
# You can specify a range of versions like '>=3.6,<3.10'
# Or a specific version like '3.8'
# Or allow any version with '*'
version = "3.10"
